# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#url: "https://cis-advising-handbook.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "/blog" # the subpath of your site, e.g. /blog
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
#theme: minima
#remote_theme: "mmistakes/minimal-mistakes@8a67ce8e41ec850f2d7c373aa47739b2abfee6f1"
remote_theme: "cis-advising-handbook/minimal-mistakes"

plugins:
  - jekyll-include-cache


title: CIS Advising Handbook
email: cis-undergrad-advising@seas.upenn.edu
description: "Guidance for undergraduates in the Penn CIS Department"
logo: "/assets/images/penn-engineering-logo.png"
words_per_minute: 200
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true # true, false (default)
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : "lunr" # lunr (default), algolia, google
lunr:
  search_within_pages: true

author:
  name             : "CIS Advising Staff"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : ""
  location         : "310 Levine Hall"
  email            :
  links:
    - label: "email the team" # "cis-undergrad-advising@seas"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:cis-undergrad-advising@seas.upenn.edu"
    - label: "connect with us!"
      icon: "fas fa-fw fa-link"
      url: "https://www.cis.upenn.edu/undergraduate/advising/"
    - label: "SEAS handbook"
      icon: "fas fa-fw fa-book-open"
      url: "https://ugrad.seas.upenn.edu/student-handbook/"

highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink: /:title/

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
      show_date: false
      # NB: we put commonly-used links here for simpler updating across the handbook
      links:
        seas_petition_form: https://upenn.bplogix.net/form.aspx?pid=e6634b2b-e441-4279-8c38-a89adb52152c&formid=202ebf6e-0adf-4554-80e9-ba5749c24320&nohome=1&completepageprompt=0&completepage=https://upenn.bplogix.net/custom/ThankYou.html&completetext= 
        cis_course_sub_form: https://apps.cis.upenn.edu/forms/student/add-ciscoursesub
        path_major_minor_form: https://upenn.bplogix.net/form.aspx?pid=e6634b2b-e441-4279-8c38-a89adb52152c&formid=8f13f1e2-eef6-491c-b45f-65e95860986c&nohome=1&completepageprompt=0&completepage=https://upenn.bplogix.net/custom/ThankYou.html&completetext=
        cis_te_form: https://apps.cis.upenn.edu/forms/student/add-tech-elective
        cis_cu_limit_form: https://upenn.bplogix.net/form.aspx?pid=e6634b2b-e441-4279-8c38-a89adb52152c&formid=7a7d9a98-b25c-47f3-9d64-930036a79f25&nohome=1&completepageprompt=0&completepage=https://upenn.bplogix.net/custom/ThankYou.html&completetext=
        cis_waitlist: https://apps.cis.upenn.edu/waitlist/student/dashboard
        seas_cu_policy: https://ugrad.seas.upenn.edu/student-handbook/undergraduate-policies/course-load/
        path_forms: https://srfs.upenn.edu/registrar/studentforms
        path_help: https://srfs.upenn.edu/path-at-penn
        ras: https://ras.seas.upenn.edu/
        ras_contacts: https://ras.seas.upenn.edu/ras-contacts-list/
        # NB: next two links are also in the `author` info above
        cis_adv_home: https://www.cis.upenn.edu/undergraduate/advising/
        seas_ugrad_hbook: https://ugrad.seas.upenn.edu/student-handbook/
        ugc_name: Joe Devietti
        ugc_email: devietti@cis.upenn.edu
        ugc_feedback_email: devietti+advisinghandbook@cis.upenn.edu
        ugc_website: https://www.cis.upenn.edu/~devietti/

# Reading Files
# include:
#   - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
   - README.md
   - TODO.txt
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
